### ISSUE TITLE
Drupal user and content

### ISSUE THREAD

**Issue by Trogie** [jhedstrom/drupalextension#135]
Hello,

I had some feature files where I create content in certain scenarios with a user 'logged in with :role role'. After that scenario, I do check certain json calls. In a last scenario I did remove the content, again with 'logged in as a user with :role role' (another user offcourse than in the earlier scenario).

Everything worked ok but since a recent update (php composer.phar update) it looks like the content created with the first scenario gets deleted after that particular scenario...

Did something change recently in drupalextension? How to solve?

**Comment by Trogie** [comment]
Hmmm my fault, had the drupal api commented out

**Comment by Trogie** [comment]
Hmmm wasn't my fault but it looks like users get always deleted after a scenario with the 'user_cancel_delete' method.

I think the drupal driver should use the drupal settings from the site it is working on: my variable user_cancel_method is set to 'user_cancel_block' and so I don't expect the content to be removed with the user.

**Comment by pfrenssen** [comment]
I'm still quite new to Behat but I believe this is intentional. After every scenario is tested all assets that were created during the scenario should be cleaned up so the website is back in the same state as before the test started.

This is why the 'user_cancel_delete' method is used: it ensures that all content created by the user is correctly removed.

There is a good reason for this: if any content or other assets stay behind then this might affect tests that run later. Imagine you have a test that creates 5 nodes with a certain keyword and then checks that the search results page contains 5 results for that keyword. This test would fail if any previous test would happen to create any node with that keyword.

If you need data created by a previous test scenario the best thing you can do is merge the two scenarios together. You can also use backgrounds to populate data to reuse in different test scenarios.

**Comment by Trogie** [comment]
Off course, but why after every scenario? Why not after a Feature or complete test run? Why not make it configurable so the tester himself can decide?

**Comment by pfrenssen** [comment]
Because every test scenario should be executable on its own. If your test scenarios are reusing data from previous test runs then they will fail if run in isolation. Also if you would make a change to test scenario 1 then suddenly test scenario 2 might fail because it relies on data from 1. It makes the test suite less reliable.

Take some time to go through the examples in the official Behat documentation: [Hooking into the test process](http://docs.behat.org/en/latest/guides/3.hooks.html). You'll see that these "@afterScenario" examples are mostly concerned with cleaning up data.

This is by the way not even a limitation of Behat, but it is common practice among all implementations of the Gherkin language. If you look up examples for Cucumber you'll also see that they clean up after each scenario.

**Comment by Trogie** [comment]
Hmmm ok... I usually have features as executable units, not the scenarios themselves.
I'll try to rewrite my tests.

How would you have a scenario then that creates content a user with X role and that checks the existence of a json call as a anonymous user?

**Comment by pfrenssen** [comment]
You could first log in as a user with role X, create the content you need, and then log out in your scenario with:

```
Given I am not logged in
```

**Comment by scottalan** [comment]
Here's a PR that will let you keep your content. https://github.com/jhedstrom/drupalextension/pull/165

**Comment by jhedstrom** [comment]
It's quite intentional that content doesn't persist between scenarios (as each scenario should always be independent of another). For scenarios that need to share common content, utilize the `background` part of feature files, which provides steps that always run before each scenario.
