### ISSUE TITLE
Where to contribute step definitions?

### ISSUE THREAD

**Issue by TravisCarden** [jhedstrom/drupalextension#343]
I'm building a collection of step definitions I need frequently on projects, and I'm wondering where I should contribute them for the community to use. See the below, for example, demonstrating a `@Then exactly the following roles should exist` and `@Then the :role_id role should be the administrator role` steps. Are there guidelines for what sort of steps are welcome in DrupalExtension? Is there somewhere else to contribute steps that don't fit here? Thanks!

![behat-scenario](https://cloud.githubusercontent.com/assets/959246/22176745/7a288b74-dfd6-11e6-8f59-9a07c5388bce.png)

**Comment by pfrenssen** [comment]
Writing step definitions is often quite trivial and we want to avoid bloat, so we try to accept only step definitions that are really useful for 80% of all projects out there, or that are very complicated to write.

I think a good guideline would be to propose step definitions in an issue, and when we get a lot of response from the community that it would be useful then we can consider it for inclusion.

**Comment by TravisCarden** [comment]
Thanks, @pfrenssen; that makes sense. The first contribution I'd like to make ([my table comparison engine](https://github.com/TravisCarden/my_devel/commit/83998431b17f405ae6f5379b4abbe0231581f1fc)) has comprehensive PHPUnit test coverage. But I see that you're not running PHPUnit on CI--you're running phpspec, which I've never used. Realistically, I'm not likely to learn it in the short term... What do you suggest?

**Comment by pfrenssen** [comment]
We use Behat for our tests :) I'm not very familiar with PHPSpec myself, from what I can see it is not really for unit testing, more for declaring the architecture.

I had a look at your table comparison engine, it seems very useful for all kinds of projects, also ones that do not use Drupal. I think it maybe warrants an extension of its own, or maybe gets integrated with one of the existing small helper extensions like the ones offered by [FriendsOfBehat](https://github.com/FriendsOfBehat). I think it would be better as an assertion class rather than a trait, something similar to `WebAssert` which is offered by the Mink extension.
If you have your own little extension you can provide PHPUnit coverage at will.

The step definitions for exactly comparing user roles are maybe a bit too specific, but I think the one for checking if a user is an administrator might be helpful, but it will have to be adapted so it works with D7 as well as D8.

**Comment by TravisCarden** [comment]
Very helpful, @pfrenssen; thanks! I'll check into those suggestions and report back here if and as appropriate.

**Comment by TravisCarden** [comment]
FYI, @pfrenssen: I've improved the interface and published [traviscarden/behat-table-comparison](https://packagist.org/packages/traviscarden/behat-table-comparison) on Packagist. I'd love feedback from anyone who uses or would like to use it!

**Comment by pfrenssen** [comment]
Wow this looks really great! A lot more advanced than I imagine it would be. This will come in really handy!
