### ISSUE TITLE
getContext() method doesn't seem to exist

### ISSUE THREAD

**Issue by phenaproxima** [jhedstrom/drupalextension#386]
After updating to Drupal Extension 3.3.0, I get this error when running acquia/lightning's tests:

Fatal error: Call to undefined method Behat\Behat\Context\Environment\UninitializedContextEnvironment::getContexts() in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/DrupalSubContextBase.php on line 64

I'm not sure what's happening here -- any ideas would be welcome.

**Comment by balsama** [comment]
I traced this problem to line 64 of DrupalSubContextBase. It thinks $environment is a \Behat\Behat\Context\Environment\InitializedContextEnvironment, but it's actually \Behat\Testwork\Environment\Environment, which doesn't have the `getContexts()` method (InitializedContextEnvironment does).

**Comment by pfrenssen** [comment]
I think this might be related to the Behat update that we did in the latest release. We were stuck on Behat 3.1 before. In Behat 3.2 a change was introduced that properly reinitializes Context classes at the start of every scenario and any code that relies on data being present in contexts from before the scenario started will now fail. Ref. https://github.com/Behat/Behat/issues/758

I had a look at one of the contexts that threw a failure in the build that was linked, and it seems that this is the cause of the problem:

https://github.com/acquia/lightning/blob/02b18b602fb75f0990f802fa8d60f2a59234f82b/src/LightningExtension/Context/BlockContext.behat.inc#L21

```
  /**
   * Gathers required contexts.
   *
   * @BeforeScenario
   */
  public function gatherContexts() {
    $this->minkContext = $this->getContext(MinkContext::class);
  }
```

The `@BeforeScenario` means this code runs before the scenario is started. I haven't looked at the actual implementation but it seems likely that the contexts are not yet initialized at that point so they cannot be retrieved from the environment.

This also seems like very inefficient code, since this will be executed at the start of every single scenario, even if the step definitions defined in the context are not even used in the scenario.

Can you try changing this so the contexts are retrieved when they are actually being used instead of on the `@BeforeScenario` hook? Something like this:

```
-    $this->minkContext->fillField('id', $id);
+   $this->getContext(MinkContext::class)->fillField('id', $id);
```

**Comment by pfrenssen** [comment]
I have proposed a PR that throws a more helpful exception, that will hopefully in the future help developers understand & debug this problem.

Can you confirm if the `@BeforeScenario` is the root of the problem?

**Comment by balsama** [comment]
@pfrenssen yes, moving the getContext calls out of @BeforeScenario fixed this. Thanks for the help.

**Comment by pfrenssen** [comment]
You're welcome! Glad to hear it has been fixed!

**Comment by kmajzlik** [comment]
Can somebody help me with this?
How to use Scenario Outline with DrupalExtension 3.3 and Behat 3.3 (both needed because running Drupal 8.4-dev)?

If i tried somehow remove this call because of UninitializedContextEnvironment class then i have 
`WebDriver\Exception\CurlExec: Curl error thrown for http POST to http://selenium-hub:4444/wd/hub/session with params`
error.

**Comment by jhedstrom** [comment]
#390 might have helped with this too.

**Comment by kmajzlik** [comment]
Thank you very much, it seems that using
`"drupal/drupal-extension": "3.3.x-dev",`
saved me.
