### ISSUE TITLE
Is there a way to automate sitemap.xml with 100's of urls in Behat or using php?

### ISSUE THREAD

**Issue by sswarupa2017** [jhedstrom/drupalextension#391]
I am trying to automate sitemap.xml with 100's of urls using behat or php. Pl. let me know if there are any out of the box API's to click through each url from sitemap and check if there are any dead links.

I have looked online and tried out some solutions online like:
        $xml = simplexml_load_file(file.xml);
        $json = json_encode($xml);
        $array = json_decode($json,TRUE);
and then tried  to dump the array and extract the urls. It see's it as one array and not 2 dimensional array.

**Comment by pfrenssen** [comment]
The BDD advocate in me would say that Behat is not the right tool for the job here since you are not testing end user behavior. But for the sake of the argument let's assume that the bots reading the sitemap are also end users :)

Yeah you could write a step definition that loads the file and loops over the entries in the sitemap, testing them all in order. Something like `@Then all the links in my sitemap are valid`. You can visit them one by one and verify they return a 200 OK.

For the actual PHP implementation you can maybe better ask on a site that is focused on helping programmers, I think stack overflow would be a good choice, you can often get some quick feedback there.

**Comment by sswarupa2017** [comment]
Thank you !!
