### ISSUE TITLE
Does Behat have out of box methods for RSS feed validation?

### ISSUE THREAD

**Issue by sswarupa2017** [jhedstrom/drupalextension#397]
Hi, I am new to Behat and have written couple of UI tests in behat 3.0 but not sure how to automate validations from RSS feed in Drupal 8.0. Any pointers to which context or extensions have methods to validate RSS content would be really helpful. Thanks in advance!

**Comment by pfrenssen** [comment]
RSS is not a Drupal-only feature so this is out of scope for Behat Drupal Extension. This question would be better asked in https://github.com/behat/behat/ but I can also answer it for you.

Ideally there would be something like a "Behat RSS Extension" or even a generic "Behat XML extension" would also do the job since RSS feeds are in XML format. Unfortunately I couldn't find either of those.

If you want to implement this yourself you can either do it inside your project in a separate `RssContext` or `XmlContext` class. Even better, you could make an actual Behat extension. That's a bit more work but then it can be reused easily in other projects by simply doing a `$ composer require sswarupa2017/rssextension` :)

I am not sure how well Mink handles XML, so it's perhaps better to do the requests yourself using Guzzle.

I would make one step definition to retrieve the RSS feed with Guzzle, and store it on a local property in the context class, something like `@When I retrieve the :name RSS feed`. 

Then you can have as many step definitions that check the contents of the feed, things like:

* `@Then I should see :number items in the RSS feed`
* `@Then I should see an article with title :title in the RSS feed`
* ...

For this you can inspect the XML using your favorite XML parsing PHP extension or library.
