### ISSUE TITLE
Drush Driver vs Drupal Driver

### ISSUE THREAD

**Issue by albertski** [jhedstrom/drupalextension#539]
When running Behat tests with the `drush` driver I noticed that it is a lot slower than the `drupal` driver.

**Drupal Driver**
```
3 scenarios (3 passed)
9 steps (9 passed)
1m8.90s (15.61Mb)
```

**Drush Driver**
```
3 scenarios (3 passed)
9 steps (9 passed)
3m50.04s (6.81Mb)
```

Is this expected behavior?

**Comment by jhedstrom** [comment]
Drush probably has more overhead, but that seems like a lot. The main intent of the drush driver is to run tests remotely (the behat code is running on a different server than the site being tested.) If that isn't necessary, then the drupal driver will be preferable since it is faster and has direct API access, so custom step definitions are easier to write.

**Comment by albertski** [comment]
This is probably because I am working locally on Docker with traefic. I suspect that's why.
