### ISSUE TITLE
Ability to bypass cookie compliance

### ISSUE THREAD

**Issue by mistermoper** [jhedstrom/drupalextension#583]
Hi.

In one project I am working on the module [eu_cookie_compliance](drupal.org/project/eu_cookie_compliance) is installed. 
There are Behat tests checking it works fine as we added customizations to the module (custom twig templates), and is a critical feature with legal issues in the case it's not working properly.

The problem comes when we want to bypass cookies in a test where we don't want to check cookies are working. One of the solutions is setting up the acceptance EU cookie compliance cookies in a @beforeScenario tag. This doesn't work well in every use case as the [authentication manager](https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php) performs a logout and remove all the cookies (with the [fastLogout](https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php#L155) method).

Thinking about this there are two possible solutions:

- Allowing configure the behat.yml file so that we could indicate which cookies we would like to preserve after doing the [fastLogout](https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Manager/DrupalAuthenticationManager.php#L155). Then that cookies could be stored in a variable before logging out, and set up back after logout. As the authentication manager is able to read the parameters of the behat.yml, it should be easy to do.

- Adding two events: @beforeLogout and @afterLogout . The contexts of the projects would be able to hook into these events so they do any action they need. It would be more flexible, allowing more special code for these use cases.

I would like to help with the project on this, let me know if some of these options are okay for you , or if there is another possible solution to this problem.

Thanks!

**Comment by pfrenssen** [comment]
So if I am reading correctly, you want to hack around the login and logout procedure to preserve the cookie state, and also hide the details of the cookie settings from the steps in the scenario?

In my experience it's better to avoid putting in place workarounds that preserve state. Also hiding state changes in `@beforeScenario` code is something that should be strictly avoided. Each scenario should spell out exactly the starting conditions using a number of `Given` steps.

The main purpose of BDD is to describe the behaviour of the UI for certain user scenarios in a way that is understandable for business stakeholders. What you are proposing seems to go contrary this philosophy.

The hooks that are provided by Behat (like `@beforeScenario`) are intended to set up purely technical aspects which are required for the test but  are not achievable through the user interface (e.g. creating a database connection, setting up a mail catcher, ensuring new data is committed in the search engine etc). They should never perform any logic that an actual user of the site can perform through the UI. Since logging in and out are steps that can be performed by a user in the UI, `@beforeLogout` and `@afterLogout` seem to be out of scope for us. 

If a scenario requires EU compliance cookies to be accepted, this should be handled in a step:

```
Scenario: Engage with the marketing team through the chat
  Given I am an anonymous user
  And I have accepted the "required, functional, performance, marketing" cookies
  When I visit the search page
  Then I should see the heading "Chat with us" in the "right sidebar"
```

I can understand if most of the project requires some or all cookies to be accepted that this can become tedious, but hiding these things in a `@beforeScenario` hook is effectively hiding essential steps from the scenario. A business stakeholder (like a helpdesk employee) following the scenario manually would not be able to achieve the same result if they didn't know that there is a missing step that needs to be followed.

Besides of this, Drupalextension only supports the login and logout mechanisms provided by Drupal core. We no longer add any new functionality that is outside what comes out of the box with Drupal core (e.g. functionality provided by contributed and custom modules). The reason for this is that Drupal can be customized in so many different ways that our scope would become infinite. But we try our best to ensure that you can test whatever custom functionality you require by providing hooks and overrides. 

If you want to hide cookie compliance interaction from your scenarios, you can achieve this by overriding the `DrupalAuthenticationManager`. You can provide whatever logic you want. Here is an example of how to do this: https://www.drupal.org/project/email_registration/issues/2843505

**Comment by mistermoper** [comment]
Thank you for the detailed explanation! Now I have it clear. 

After understanding all the points I agree that setting up the cookies with a hook would hide some essential steps on the tests.  Also I understand that the drupal extension should only take responsibility for core functionalities. 

Knowing that hooks are only intended for actions that the real users can't do, I'll try to develop a step that wraps the log in step meanwhile it accepts cookies, which will be clearer to understand. Also, it could be possible to contribute.

Closing.
